version: "3.3"

services:
  backend:
    image: node:lts-slim
    #privileged: true
    working_dir: "/app"
    user: "${UID}:${GID}"
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      #- /dev:/dev
    devices:
      #- "/dev/bus/usb:/dev/bus/usb"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
